Changes to development
Abner21/Building-with-Backgrounds-and-Gradients pull request #1
Opened 2019-07-24 13:29 UTC by Abner21

2019-07-24 23:01 UTC, samgaco requested changes
### Hi @Abner21 :vulcan_salute: 

Great job so far :clap: It is looking good :100:  here are some changes to be made:

* The **elements in the** **navigation bar** should be buttons and be arranged with either floats or display flex.
* The search `<input>` tag should have the[ focus effect](https://www.w3schools.com/cssref/sel_focus.asp) enabled in the CSS file.
*  The _firstIphone_, _secondIphone_, etc. should be within the footer and those '<div>' tags should be wrapped within `<a>` tags so they are clickable.
* Add project description in the **read me file**, is also suggested to add your contact and a live-demo of the site for example. [Here ](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)you have an example template of a readme file.
* The main content (from the navigation bar until the footer) should be wrapped in a `<main>` tag, and the background of this tag should be the main image of the site.
* Is recommended to have the lists in the footer arranged with floats or display flex.

### That's it. Please :pray: work on these changes and submit back for another code review when you are done. Good spirit and happy coding! :muscle:

2019-07-24 23:01 UTC, samgaco commented on GradientsProject/index.html
> +          -->
You should avoid having this --> arrows within the code.

2019-07-25 17:37 UTC, mosaaleb commented
Reviewing

2019-07-25 18:01 UTC, mosaaleb requested changes
## Hi @Abner21 

#### Great job :clap:. I liked that you took care of different browser vendors by using vendor prefixes. The UI is clean. You have met most of the requirements, yet there is minor requirements needs to be done before moving on. See my comments below.


Also, 

### General:

- [ ] The project should have a descriptive README.md
- [ ] Let's make sure that we have good style guidelines by using [stickler](https://github.com/microverseinc/linters-config/tree/master/css).

Please submit a new code review once these requirements are met.

#### Happy coding :computer:

2019-07-25 18:01 UTC, mosaaleb commented on index.html
> +      <a class="container" href="index.html">Watch the "Your Verse" film and explore the stories <i class="far fa-play-circle"></i></a>
There text 'watch the ....' should be image.
- [ ] Each link is an `<a>` HTML tag, with a `<div>` tag inside it.
- [ ] The `<div>` tag  inside the `<a>` tag should use an image as background -- [ ] The text on the original page is actually an image

2019-07-25 18:01 UTC, mosaaleb commented on index.html
> +      <div class="lastItem">
[optional]: You can use css `last-child` selector instead of defining a new `lastItem` class.

2019-07-25 22:41 UTC, samgaco commented
### Hi @Abner21 :hand: 

### The project looks perfect now and is approved :clap: 

**There is a problem though. The branch has a conflict, so you should solve that before merging to the master branch and submitting the completion form.**

Anyways, congratulations on finishing your first solo project. :muscle:

2019-07-25 23:04 UTC, Abner21 commented
Thanks for the valuable feedback, guys!

On Thu, Jul 25, 2019 at 4:41 PM samgaco <notifications@github.com> wrote:

> Hi @Abner21 <https://github.com/Abner21> ✋ The project looks perfect now
> and is approved 👏
>
> *There is a problem though. The branch has a conflict, so you should solve
> that before merging to the master branch and submitting the completion
> form.*
>
> Anyways, congratulations on finishing your first solo project. 💪
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Abner21/Building-with-Backgrounds-and-Gradients/pull/1?email_source=notifications&email_token=ALEZDXXXPFTRZYFU6PV2CW3QBITZXA5CNFSM4IGQCNZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD227GPY#issuecomment-515240767>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALEZDXRPAWITOVFYBL7VGIDQBITZXANCNFSM4IGQCNZA>
> .
>

2019-07-25 23:07 UTC, merged